Controllers/ProductDealsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VisionStore.Data.Cart;
using VisionStore.Data.ViewModels;
using VisionStore.Models;
using VisionStore.Services.IServices;

namespace VisionStore.Controllers
{
    public class ProductDealsController : Controller
    {
        private readonly IProductsService _productsService;
        private readonly ProductDeals _productDeals;

        public ProductDealsController(IProductsService productsService,ProductDeals productDeals)
        {
            _productsService = productsService;
            _productDeals = productDeals;
        }

     
        public IActionResult Index()
        {
            var items = _productDeals.GetProductDealsItems();
            _productDeals.ProductDealsItems = items;
            

            ShoppingCartVM productVm = new()
            {
                ProductDeals = _productDeals,
                
            };
            
            

            return View(productVm);
        }
       
        [AutoValidateAntiforgeryToken]
        [Authorize]
        public async Task<IActionResult> AddToProductDeals(int id,ProductDealsItem productDeals)
        {
           
            var item = await _productsService.GetByIdAsync(id);

            if(item != null)
            {
                _productDeals.AddItemToDeal(item);
            }
            return View();
        }

        [Authorize]
        public async Task<IActionResult> RemoveItemFromDeal(int id)
        {
            var item = await _productsService.GetByIdAsync(id);

            if (item != null)
            {
                _productDeals.RemoveItemFromDeal(item);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/ProductDeals/AddToProductDeals.cshtml
@model ProductDealsItem

@{
    ViewData["Title"] = "Add Product to Deal";
}
<div class="admin-container row justify-content-center mt-5 mb-5">
    <div class="col-md-4">
      <form enctype="multipart/form-data" asp-action="Index">
            <h3>Add new price to this item</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      

           
            <div class="row">
                <div class="form-group col">
                    <label asp-for="NewPrice" class="control-label"></label>
                    <input asp-for="NewPrice" class="form-control" />
                    <span asp-validation-for="NewPrice" class="text-danger"></span>
                </div>
               
            </div>
         
            <div class="form-group d-flex justify-content-between">
                <input type="submit" value="Add" class="btn btn-primary col-5" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script type="text/javascript">
 $(".custom-file-input").on("change", function () {
     var fileName = $(productImage).val().split("\\").pop();
     $(productImage).siblings(".custom-file-label").addClass("selected").html(fileName);
 });
    
</script>
}

Views/ProductDeals/Index.cshtml
@using VisionStore.Data.ViewModels;
@model ShoppingCartVM;

@{
    ViewData["Title"] = "Product Deals Summary";
}
<html>

<body>
    <div class="admin-container row flex-column align-items-center justify-content-center">
    <h3>Product Deals Summary</h3>
     
    <table class="table table-responsive row col-9" style="padding:100px;">
          <thead>
            <tr>
                <th>Product Image</th>
                <th>Product</th>
                <th>Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var deal in Model.ProductDeals.ProductDealsItems)
            {
                
                <tr>
                    <td> <img src="~/img/@deal.Products.ImageUrl" style="width:100px; height:100px" /></td>
                    <td style='text-align:center; vertical-align:middle'>@deal.Products.Title</td>
                    <td style='text-align:center; vertical-align:middle'> @deal.NewPrice</td>

                    <td style='text-align:center; vertical-align:middle'>
                        <a class="text-danger" asp-controller="ProductDeals" asp-action="RemoveItemFromDeal" asp-route-id="@deal.Products.ProductId">  
                   <i class="bi bi-trash"></i>
                        </a>                        
                    </td> 
                  

                </tr>
                
            }

        </tbody>

    

    </table>
 
    </div>

    </body>
    </html>